language: php

php:
  - 7
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
